import { MealPlanImportType } from "@/schemas/meal-plan.schema";

export function getInitialSeedPlan(startDateStr = "2026-09-14"): MealPlanImportType {
  return {
    version: "1.0",
    plan: {
      name: "ตารางอาหารคลีนลดน้ำหนัก - สัปดาห์ที่ 1",
      description: "แผนอาหารเน้นโปรตีนสูง ทำง่ายจากวัตถุดิบในตู้เย็น เหมาะสำหรับลดไขมันและรักษากล้ามเนื้อ",
      startDate: startDateStr,
      days: [
        {
          day: 1,
          label: "จันทร์",
          date: startDateStr,
          meals: [
            {
              externalId: "mon-breakfast",
              type: "breakfast",
              time: "07:30",
              name: "ไข่ต้ม + ข้าว + แตงกวา",
              description: "มื้อเช้าพลังงานสะอาด ทำง่ายและอิ่มนาน",
              prepTime: 10,
              nutrition: { calories: 350, protein: 18, carbs: 45, fat: 10 },
              ingredients: [
                { name: "ไข่", amount: 2, unit: "ฟอง", category: "protein" },
                { name: "ข้าวสวย", amount: 1, unit: "ทัพพี", category: "carb" },
                { name: "แตงกวา", amount: 1, unit: "ลูก", category: "vegetable" },
              ],
              instructions: [
                "ต้มน้ำให้เดือด ใส่ไข่ลงไปต้มประมาณ 7-8 นาที เพื่อให้ได้ไข่ยางมะตูมพอดี",
                "ตักไข่แช่น้ำเย็นทันทีเพื่อแกะเปลือกง่าย",
                "หั่นแตงกวาเป็นแว่นพอดีคำ เสิร์ฟพร้อมข้าวสวยร้อนๆ และไข่ต้ม เหยาะซีอิ๊วขาวเล็กน้อย",
              ],
              tags: ["high-protein", "quick", "meal-prep"],
            },
            {
              externalId: "mon-lunch",
              type: "lunch",
              time: "12:00",
              name: "อกไก่ย่าง + บรอกโคลี",
              description: "อกไก่เนื้อนุ่มย่างกระทะ พร้อมบรอกโคลีลวกหวานกรอบ",
              prepTime: 20,
              nutrition: { calories: 420, protein: 45, carbs: 15, fat: 8 },
              ingredients: [
                { name: "อกไก่", amount: 200, unit: "g", category: "protein" },
                { name: "บรอกโคลี", amount: 150, unit: "g", category: "vegetable" },
                { name: "พริกไทย", amount: 1, unit: "ช้อนชา", category: "seasoning" },
                { name: "ซีอิ๊วขาว", amount: 1, unit: "ช้อนโต๊ะ", category: "seasoning" },
              ],
              instructions: [
                "หมักอกไก่ด้วยซีอิ๊วขาวและพริกไทยป่น 10 นาที",
                "ตั้งกระทะเทฟลอนไฟกลาง ทาน้ำมันมะกอกบางๆ นำอกไก่ลงย่างจนสุกทั้งสองด้าน (ข้างละ 5-6 นาที)",
                "ลวกบรอกโคลีในน้ำเดือดผสมเกลือ 2 นาที แล้วน็อคน้ำเย็นเพื่อให้สียังเขียวสด",
                "หั่นไก่จัดใส่จานพร้อมบรอกโคลี",
              ],
              tags: ["high-protein", "low-carb"],
            },
            {
              externalId: "mon-dinner",
              type: "dinner",
              time: "18:30",
              name: "หมูสับผัดกะหล่ำปลี",
              description: "กะหล่ำปลีกรอบหวาน ผัดกับหมูสับใช้น้ำมันน้อย",
              prepTime: 15,
              nutrition: { calories: 380, protein: 30, carbs: 18, fat: 12 },
              ingredients: [
                { name: "หมูสับ", amount: 150, unit: "g", category: "protein" },
                { name: "กะหล่ำปลี", amount: 200, unit: "g", category: "vegetable" },
                { name: "กระเทียม", amount: 3, unit: "กลีบ", category: "seasoning" },
                { name: "ซีอิ๊วขาว", amount: 1, unit: "ช้อนโต๊ะ", category: "seasoning" },
              ],
              instructions: [
                "ซอยกะหล่ำปลีเป็นชิ้นพอดีคำ ล้างน้ำให้สะอาดและสะเด็ดน้ำ",
                "บุบกระเทียมลงผัดในกระทะให้หอม ใส่หมูสับลงไปยีจนเกือบสุก",
                "เร่งไฟแรง ใส่กะหล่ำปลีลงไป ปรุงรสด้วยซีอิ๊วขาว ผัดเร็วๆ ให้กะหล่ำสลดแต่ยังกรอบ",
              ],
              tags: ["quick", "easy-dinner"],
            },
          ],
        },
        {
          day: 2,
          label: "อังคาร",
          date: "2026-09-15",
          meals: [
            {
              externalId: "tue-breakfast",
              type: "breakfast",
              time: "07:30",
              name: "ไข่คน + อกไก่",
              description: "ไข่คนเนื้อเนียนนุ่มคู่กับอกไก่ฉีก",
              prepTime: 12,
              nutrition: { calories: 360, protein: 35, carbs: 5, fat: 14 },
              ingredients: [
                { name: "ไข่", amount: 2, unit: "ฟอง", category: "protein" },
                { name: "อกไก่", amount: 100, unit: "g", category: "protein" },
                { name: "ต้นหอม", amount: 1, unit: "ต้น", category: "vegetable" },
              ],
              instructions: [
                "ตอกไข่ใส่ชาม ตีให้เข้ากัน ปรุงรสด้วยเกลือและพริกไทยเล็กน้อย",
                "ฉีกอกไก่ต้มสุกเป็นเส้นๆ",
                "ตั้งกระทะไฟอ่อน เทไข่ลงไป ใช้ตะหลิวดันไข่จากขอบเข้าหากลางเบาๆ จนเซ็ตตัวนุ่ม",
                "ใส่อกไก่และโรยต้นหอมซอย ยกขึ้นทันที",
              ],
              tags: ["high-protein", "quick"],
            },
            {
              externalId: "tue-lunch",
              type: "lunch",
              time: "12:00",
              name: "สันนอกหมูผัดหอมหัวใหญ่",
              description: "เนื้อหมูสันนอกไร้มัน ผัดกับหอมใหญ่รสหวานธรรมชาติ",
              prepTime: 18,
              nutrition: { calories: 430, protein: 40, carbs: 20, fat: 10 },
              ingredients: [
                { name: "หมูสันนอก", amount: 200, unit: "g", category: "protein" },
                { name: "หอมหัวใหญ่", amount: 1, unit: "หัว", category: "vegetable" },
                { name: "ซีอิ๊วขาว", amount: 1, unit: "ช้อนโต๊ะ", category: "seasoning" },
                { name: "พริกไทย", amount: 1, unit: "ช้อนชา", category: "seasoning" },
              ],
              instructions: [
                "หั่นหมูสันนอกเป็นชิ้นพอดีคำ ซอยหอมหัวใหญ่ตามยาว",
                "ผัดหอมใหญ่ในกระทะจนเริ่มใสและมีกลิ่นหอมหวาน",
                "ใส่หมูสันนอกลงไปผัด ปรุงรสด้วยซีอิ๊วขาวและพริกไทย ผัดจนสุกทั่ว",
              ],
              tags: ["meal-prep", "lean-protein"],
            },
            {
              externalId: "tue-dinner",
              type: "dinner",
              time: "18:30",
              name: "ต้มจืดหมูสับผักกาดขาว",
              description: "ซุปใสร้อนๆ คล่องคอ ย่อยง่าย เหมาะสำหรับมื้อเย็น",
              prepTime: 20,
              nutrition: { calories: 310, protein: 28, carbs: 12, fat: 8 },
              ingredients: [
                { name: "หมูสับ", amount: 150, unit: "g", category: "protein" },
                { name: "ผักกาดขาว", amount: 200, unit: "g", category: "vegetable" },
                { name: "ผักชี", amount: 1, unit: "ต้น", category: "vegetable" },
                { name: "ซีอิ๊วขาว", amount: 1, unit: "ช้อนโต๊ะ", category: "seasoning" },
              ],
              instructions: [
                "หมักหมูสับด้วยซีอิ๊วขาวและพริกไทยเล็กน้อย ปั้นเป็นก้อนกลม",
                "ต้มน้ำในหม้อให้เดือด ใส่หมูสับลงไป คอยช้อนฟองออกให้น้ำซุปใส",
                "ใส่ผักกาดขาวหั่นท่อน ต้มต่อ 3-4 นาทีจนผักนุ่ม โรยผักชีตักเสิร์ฟ",
              ],
              tags: ["comfort-food", "low-calorie"],
            },
          ],
        },
        {
          day: 3,
          label: "พุธ",
          date: "2026-09-16",
          meals: [
            {
              externalId: "wed-breakfast",
              type: "breakfast",
              time: "07:30",
              name: "ไข่ต้ม + มะเขือเทศ",
              description: "สดชื่นยามเช้าด้วยไลโคปีนและโปรตีนเต็มฟอง",
              prepTime: 10,
              nutrition: { calories: 280, protein: 18, carbs: 15, fat: 10 },
              ingredients: [
                { name: "ไข่", amount: 2, unit: "ฟอง", category: "protein" },
                { name: "มะเขือเทศ", amount: 2, unit: "ลูก", category: "vegetable" },
                { name: "ข้าวสวย", amount: 0.5, unit: "ทัพพี", category: "carb" },
              ],
              instructions: [
                "ต้มไข่ในน้ำเดือด 8 นาที ตักแช่น้ำเย็นแล้วปอกเปลือก",
                "หั่นมะเขือเทศสดเป็นเสี้ยว จัดใส่จานพร้อมไข่ต้มและข้าวสวย",
              ],
              tags: ["quick", "antioxidant"],
            },
            {
              externalId: "wed-lunch",
              type: "lunch",
              time: "12:00",
              name: "กะเพราอกไก่",
              description: "เมนูยอดฮิตปรับสูตรคลีน ใช้น้ำเปล่าผัดแทนน้ำมันเยอะ",
              prepTime: 15,
              nutrition: { calories: 410, protein: 42, carbs: 35, fat: 6 },
              ingredients: [
                { name: "อกไก่", amount: 200, unit: "g", category: "protein" },
                { name: "กะเพรา", amount: 1, unit: "กำมือ", category: "vegetable" },
                { name: "กระเทียม", amount: 3, unit: "กลีบ", category: "seasoning" },
                { name: "ข้าวสวย", amount: 1, unit: "ทัพพี", category: "carb" },
              ],
              instructions: [
                "สับอกไก่หยาบๆ โขลกพริกกระเทียมพอแหลก",
                "ผัดพริกกระเทียมในกระทะ ใส่อกไก่ลงไปผัดจนสุก ปรุงด้วยซีอิ๊วขาว",
                "ใส่ใบกะเพรา เร่งไฟแรง ปิดเตาทันที ผัดตลบ 2-3 ครั้ง เสิร์ฟพร้อมข้าวสวย",
              ],
              tags: ["high-protein", "thai-favorite"],
            },
            {
              externalId: "wed-dinner",
              type: "dinner",
              time: "18:30",
              name: "สันนอกย่าง + ผัก",
              description: "หมูสันนอกย่างกลิ่นหอม พร้อมแตงกวาและแครอทสด",
              prepTime: 20,
              nutrition: { calories: 370, protein: 38, carbs: 12, fat: 9 },
              ingredients: [
                { name: "หมูสันนอก", amount: 180, unit: "g", category: "protein" },
                { name: "แครอท", amount: 0.5, unit: "หัว", category: "vegetable" },
                { name: "แตงกวา", amount: 1, unit: "ลูก", category: "vegetable" },
              ],
              instructions: [
                "หมักหมูสันนอกด้วยเกลือและพริกไทย",
                "ย่างบนกระทะจนสุกเหลืองน่ารับประทาน",
                "หั่นเสิร์ฟพร้อมแครอทและแตงกวาหั่นแท่ง",
              ],
              tags: ["low-carb", "clean-eating"],
            },
          ],
        },
        {
          day: 4,
          label: "พฤหัสบดี",
          date: "2026-09-17",
          meals: [
            {
              externalId: "thu-breakfast",
              type: "breakfast",
              time: "07:30",
              name: "ไข่เจียวหมูสับ (คลีน)",
              description: "ไข่เจียวหมูสับแบบทอดด้วยสเปรย์น้ำมันน้อย",
              prepTime: 15,
              nutrition: { calories: 390, protein: 28, carbs: 8, fat: 16 },
              ingredients: [
                { name: "ไข่", amount: 2, unit: "ฟอง", category: "protein" },
                { name: "หมูสับ", amount: 80, unit: "g", category: "protein" },
                { name: "ต้นหอม", amount: 1, unit: "ต้น", category: "vegetable" },
              ],
              instructions: [
                "ตีไข่ผสมกับหมูสับและต้นหอมซอย ปรุงรสด้วยซีอิ๊วขาวเล็กน้อย",
                "ฉีดสเปรย์น้ำมันในกระทะเทฟลอนไฟกลาง เทส่วนผสมลงทอดจนสุกฟูทั้งสองด้าน",
              ],
              tags: ["high-protein", "thai-comfort"],
            },
            {
              externalId: "thu-lunch",
              type: "lunch",
              time: "12:00",
              name: "อกไก่ผัดเห็ด",
              description: "อกไก่นุ่มผัดเห็ดออรินจิและเห็ดเข็มทอง กรุบกรอบรสกลมกล่อม",
              prepTime: 18,
              nutrition: { calories: 390, protein: 44, carbs: 16, fat: 7 },
              ingredients: [
                { name: "อกไก่", amount: 200, unit: "g", category: "protein" },
                { name: "เห็ดออรินจิ", amount: 100, unit: "g", category: "vegetable" },
                { name: "เห็ดเข็มทอง", amount: 100, unit: "g", category: "vegetable" },
                { name: "ซีอิ๊วขาว", amount: 1, unit: "ช้อนโต๊ะ", category: "seasoning" },
              ],
              instructions: [
                "หั่นเห็ดออรินจิเป็นแว่น และตัดโคนเห็ดเข็มทอง ล้างให้สะอาด",
                "ผัดอกไก่ในกระทะจนสุก ใส่เห็ดทั้งสองชนิดลงไปผัด",
                "ปรุงรสด้วยซีอิ๊วขาว ผัดจนเห็ดสุกนิ่มหอม",
              ],
              tags: ["high-fiber", "high-protein"],
            },
            {
              externalId: "thu-dinner",
              type: "dinner",
              time: "18:30",
              name: "หมูสับผัดไข่",
              description: "เมนูไข่ผัดหมูสับกลิ่นหอมกระทะ ทำง่ายใน 10 นาที",
              prepTime: 12,
              nutrition: { calories: 340, protein: 30, carbs: 6, fat: 12 },
              ingredients: [
                { name: "หมูสับ", amount: 120, unit: "g", category: "protein" },
                { name: "ไข่", amount: 2, unit: "ฟอง", category: "protein" },
                { name: "หอมหัวใหญ่", amount: 0.5, unit: "หัว", category: "vegetable" },
              ],
              instructions: [
                "ผัดหอมหัวใหญ่และหมูสับจนสุก",
                "ตอกไข่ลงไป ยีให้กระจายทั่วเนื้อหมู รอให้ไข่เซ็ตตัวแล้วคลุกเคล้าให้เข้ากัน",
              ],
              tags: ["quick", "budget-friendly"],
            },
          ],
        },
        {
          day: 5,
          label: "ศุกร์",
          date: "2026-09-18",
          meals: [
            {
              externalId: "fri-breakfast",
              type: "breakfast",
              time: "07:30",
              name: "ไข่ + อกไก่",
              description: "คอมโบโปรตีนเน้นๆ อิ่มเต็มที่ต้อนรับเช้าวันศุกร์",
              prepTime: 12,
              nutrition: { calories: 370, protein: 40, carbs: 10, fat: 11 },
              ingredients: [
                { name: "ไข่", amount: 2, unit: "ฟอง", category: "protein" },
                { name: "อกไก่", amount: 120, unit: "g", category: "protein" },
                { name: "แตงกวา", amount: 1, unit: "ลูก", category: "vegetable" },
              ],
              instructions: [
                "ทำไข่ดาวน้ำหรือไข่ต้มตามชอบ",
                "นาบอกไก่ในกระทะจนสุก จัดเสิร์ฟคู่กันพร้อมแตงกวาแช่เย็น",
              ],
              tags: ["high-protein", "muscle-fuel"],
            },
            {
              externalId: "fri-lunch",
              type: "lunch",
              time: "12:00",
              name: "สันนอกหมูพริกไทยดำ",
              description: "สันนอกหมูหมักพริกไทยดำบดหยาบ หอมเข้มข้นถึงรส",
              prepTime: 20,
              nutrition: { calories: 440, protein: 42, carbs: 18, fat: 11 },
              ingredients: [
                { name: "หมูสันนอก", amount: 200, unit: "g", category: "protein" },
                { name: "พริกไทย", amount: 2, unit: "ช้อนชา", category: "seasoning" },
                { name: "หอมหัวใหญ่", amount: 0.5, unit: "หัว", category: "vegetable" },
                { name: "ซีอิ๊วขาว", amount: 1, unit: "ช้อนโต๊ะ", category: "seasoning" },
              ],
              instructions: [
                "หมักหมูสันนอกด้วยพริกไทยดำบดและซีอิ๊วขาว 15 นาที",
                "ผัดหอมหัวใหญ่แล้วใส่หมูลงไปผัดจนสุกเกรียมสวยงาม",
              ],
              tags: ["flavor-packed", "high-protein"],
            },
            {
              externalId: "fri-dinner",
              type: "dinner",
              time: "18:30",
              name: "ต้มจืดอกไก่",
              description: "น้ำแกงใสอกไก่ต้มหวานธรรมชาติ อุ่นท้องยามค่ำคืน",
              prepTime: 20,
              nutrition: { calories: 310, protein: 38, carbs: 10, fat: 5 },
              ingredients: [
                { name: "อกไก่", amount: 180, unit: "g", category: "protein" },
                { name: "กะหล่ำปลี", amount: 150, unit: "g", category: "vegetable" },
                { name: "แครอท", amount: 0.5, unit: "หัว", category: "vegetable" },
              ],
              instructions: [
                "หั่นอกไก่เป็นชิ้น ต้มในน้ำเดือดพร้อมแครอท ช้อนฟองสม่ำเสมอ",
                "ใส่กะหล่ำปลีลงไปต้มจนนุ่ม ปรุงรสด้วยซีอิ๊วขาวเบาๆ",
              ],
              tags: ["comfort-food", "low-fat"],
            },
          ],
        },
        {
          day: 6,
          label: "เสาร์",
          date: "2026-09-19",
          meals: [
            {
              externalId: "sat-breakfast",
              type: "breakfast",
              time: "08:30",
              name: "ไข่คนหมูสับ",
              description: "อาหารเช้าวันหยุดแสนอร่อย ไข่คนนุ่มละมุนผสมหมูสับปรุงรส",
              prepTime: 15,
              nutrition: { calories: 380, protein: 32, carbs: 6, fat: 15 },
              ingredients: [
                { name: "ไข่", amount: 2, unit: "ฟอง", category: "protein" },
                { name: "หมูสับ", amount: 100, unit: "g", category: "protein" },
                { name: "ต้นหอม", amount: 1, unit: "ต้น", category: "vegetable" },
              ],
              instructions: [
                "ผัดหมูสับในกระทะให้สุกก่อน พักไว้",
                "ตีไข่ เทลงในกระทะไฟอ่อน ค่อยๆ คนเบาๆ เมื่อไข่เริ่มจับตัวให้ใส่หมูสับและต้นหอมลงไป",
              ],
              tags: ["weekend-brunch", "comfort-food"],
            },
            {
              externalId: "sat-lunch",
              type: "lunch",
              time: "12:30",
              name: "อกไก่ย่าง",
              description: "อกไก่ย่างเกลือพริกไทย พร้อมสลัดแตงกวาและมะเขือเทศ",
              prepTime: 20,
              nutrition: { calories: 400, protein: 45, carbs: 12, fat: 7 },
              ingredients: [
                { name: "อกไก่", amount: 200, unit: "g", category: "protein" },
                { name: "แตงกวา", amount: 1, unit: "ลูก", category: "vegetable" },
                { name: "มะเขือเทศ", amount: 1, unit: "ลูก", category: "vegetable" },
              ],
              instructions: [
                "ย่างอกไก่บนกระทะให้สุกหอมทั้งสองด้าน",
                "หั่นแตงกวาและมะเขือเทศ เสิร์ฟเคียงข้างอกไก่ย่าง",
              ],
              tags: ["clean-eating", "high-protein"],
            },
            {
              externalId: "sat-dinner",
              type: "dinner",
              time: "18:30",
              name: "สุกี้แห้งไก่",
              description: "สุกี้แห้งสูตรแคลอรีต่ำ อัดแน่นด้วยผักกาดขาวและเห็ด",
              prepTime: 20,
              nutrition: { calories: 390, protein: 42, carbs: 22, fat: 8 },
              ingredients: [
                { name: "อกไก่", amount: 180, unit: "g", category: "protein" },
                { name: "ไข่", amount: 1, unit: "ฟอง", category: "protein" },
                { name: "ผักกาดขาว", amount: 150, unit: "g", category: "vegetable" },
                { name: "เห็ดเข็มทอง", amount: 100, unit: "g", category: "vegetable" },
              ],
              instructions: [
                "ผัดอกไก่ในกระทะจนสุก ใส่ผักกาดขาวและเห็ดเข็มทองลงไป",
                "ตอกไข่ลงไปผัดคลุกเคล้าให้เข้ากัน เติมน้ำจิ้มสุกี้พอประมาณ (1 ช้อนโต๊ะ)",
              ],
              tags: ["low-calorie", "high-volume"],
            },
          ],
        },
        {
          day: 7,
          label: "อาทิตย์",
          date: "2026-09-20",
          meals: [
            {
              externalId: "sun-breakfast",
              type: "breakfast",
              time: "08:30",
              name: "ไข่ + โปรตีน",
              description: "มื้อเช้าเตรียมพร้อมสำหรับสัปดาห์ใหม่ ไข่ต้ม 2 ฟองและอกไก่ฉีก",
              prepTime: 12,
              nutrition: { calories: 360, protein: 38, carbs: 8, fat: 12 },
              ingredients: [
                { name: "ไข่", amount: 2, unit: "ฟอง", category: "protein" },
                { name: "อกไก่", amount: 100, unit: "g", category: "protein" },
                { name: "แตงกวา", amount: 1, unit: "ลูก", category: "vegetable" },
              ],
              instructions: [
                "ต้มไข่ยางมะตูม ฉีกอกไก่ต้ม วางเคียงกับแตงกวาสด",
              ],
              tags: ["meal-prep", "high-protein"],
            },
            {
              externalId: "sun-lunch",
              type: "lunch",
              time: "12:30",
              name: "สันนอกย่าง",
              description: "สเต๊กหมูสันนอกย่างกระทะ เสิร์ฟพร้อมบรอกโคลี",
              prepTime: 20,
              nutrition: { calories: 430, protein: 42, carbs: 14, fat: 11 },
              ingredients: [
                { name: "หมูสันนอก", amount: 200, unit: "g", category: "protein" },
                { name: "บรอกโคลี", amount: 150, unit: "g", category: "vegetable" },
                { name: "พริกไทย", amount: 1, unit: "ช้อนชา", category: "seasoning" },
              ],
              instructions: [
                "หมักหมูสันนอกด้วยพริกไทยและเกลือ นำลงย่างบนกระทะให้สุกพอดี",
                "ลวกบรอกโคลีเสิร์ฟเคียงข้างกัน",
              ],
              tags: ["sunday-steak", "lean-muscle"],
            },
            {
              externalId: "sun-dinner",
              type: "dinner",
              time: "18:30",
              name: "กะเพราหมูสับ (คลีน)",
              description: "ปิดท้ายสัปดาห์ด้วยกะเพราหมูสับรสจัดจ้าน ผัดน้ำมันน้อย",
              prepTime: 15,
              nutrition: { calories: 410, protein: 32, carbs: 32, fat: 10 },
              ingredients: [
                { name: "หมูสับ", amount: 150, unit: "g", category: "protein" },
                { name: "กะเพรา", amount: 1, unit: "กำมือ", category: "vegetable" },
                { name: "กระเทียม", amount: 3, unit: "กลีบ", category: "seasoning" },
                { name: "ข้าวสวย", amount: 1, unit: "ทัพพี", category: "carb" },
              ],
              instructions: [
                "โขลกพริกกระเทียม ผัดกับหมูสับในกระทะจนสุก ปรุงรสด้วยซีอิ๊วขาว",
                "ใส่ใบกะเพราสด คลุกเคล้าอย่างรวดเร็ว ตักราดข้าวสวยร้อนๆ",
              ],
              tags: ["thai-favorite", "flavor-packed"],
            },
          ],
        },
      ],
    },
  };
}
